language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "2.7"
      env: TOXENV=docs

install: "pip install tox"
script: tox

addons:
  apt:
    packages:
    - pandoc

notifications:
  email:
    on_success: never
    on_failure: always

sudo: false
